version: '2'
services:
  app:
    image: tr_api
    build: .
    ports:
      - '4000:4000'
    volumes:
      - '.:/app'
    depends_on:
      - db
  db:
    image: 'postgres:9'
    volumes:
      - ./postgres_db_data:/var/lib/postgresql/data
